// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package models

import (
	"context"
)

// iteratorForInsertOrderTags implements pgx.CopyFromSource.
type iteratorForInsertOrderTags struct {
	rows                 []InsertOrderTagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertOrderTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertOrderTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Orderid,
		r.rows[0].Tag,
	}, nil
}

func (r iteratorForInsertOrderTags) Err() error {
	return nil
}

func (q *Queries) InsertOrderTags(ctx context.Context, arg []InsertOrderTagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ordertags"}, []string{"orderid", "tag"}, &iteratorForInsertOrderTags{rows: arg})
}

// iteratorForInsertRecruits implements pgx.CopyFromSource.
type iteratorForInsertRecruits struct {
	rows                 []InsertRecruitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRecruits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRecruits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Recruitid,
		r.rows[0].Companyname,
		r.rows[0].Enterprisename,
		r.rows[0].Logourl,
		r.rows[0].Citynamelist,
		r.rows[0].Updatetime,
		r.rows[0].Companytype,
		r.rows[0].Endtime,
		r.rows[0].Content,
		r.rows[0].Url,
		r.rows[0].Begintime,
		r.rows[0].Overseasstudent,
		r.rows[0].Domesticstudent,
		r.rows[0].Releasesource,
	}, nil
}

func (r iteratorForInsertRecruits) Err() error {
	return nil
}

func (q *Queries) InsertRecruits(ctx context.Context, arg []InsertRecruitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recruit"}, []string{"recruitid", "companyname", "enterprisename", "logourl", "citynamelist", "updatetime", "companytype", "endtime", "content", "url", "begintime", "overseasstudent", "domesticstudent", "releasesource"}, &iteratorForInsertRecruits{rows: arg})
}
