// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Accountbalancetype string

const (
	AccountbalancetypeBalance           Accountbalancetype = "balance"
	AccountbalancetypeBalanceleft       Accountbalancetype = "balanceleft"
	AccountbalancetypeBalanceright      Accountbalancetype = "balanceright"
	AccountbalancetypeBalancetriplelock Accountbalancetype = "balancetriplelock"
	AccountbalancetypeBalancetriple     Accountbalancetype = "balancetriple"
	AccountbalancetypePendingreturn     Accountbalancetype = "pendingreturn"
)

func (e *Accountbalancetype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Accountbalancetype(s)
	case string:
		*e = Accountbalancetype(s)
	default:
		return fmt.Errorf("unsupported scan type for Accountbalancetype: %T", src)
	}
	return nil
}

type NullAccountbalancetype struct {
	Accountbalancetype Accountbalancetype `json:"accountbalancetype"`
	Valid              bool               `json:"valid"` // Valid is true if Accountbalancetype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountbalancetype) Scan(value interface{}) error {
	if value == nil {
		ns.Accountbalancetype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Accountbalancetype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountbalancetype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Accountbalancetype), nil
}

type Accountpartition string

const (
	AccountpartitionL Accountpartition = "L"
	AccountpartitionR Accountpartition = "R"
)

func (e *Accountpartition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Accountpartition(s)
	case string:
		*e = Accountpartition(s)
	default:
		return fmt.Errorf("unsupported scan type for Accountpartition: %T", src)
	}
	return nil
}

type NullAccountpartition struct {
	Accountpartition Accountpartition `json:"accountpartition"`
	Valid            bool             `json:"valid"` // Valid is true if Accountpartition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountpartition) Scan(value interface{}) error {
	if value == nil {
		ns.Accountpartition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Accountpartition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountpartition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Accountpartition), nil
}

type Accountstatus string

const (
	AccountstatusINIT   Accountstatus = "INIT"
	AccountstatusACTIVE Accountstatus = "ACTIVE"
	AccountstatusCLOSED Accountstatus = "CLOSED"
)

func (e *Accountstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Accountstatus(s)
	case string:
		*e = Accountstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Accountstatus: %T", src)
	}
	return nil
}

type NullAccountstatus struct {
	Accountstatus Accountstatus `json:"accountstatus"`
	Valid         bool          `json:"valid"` // Valid is true if Accountstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Accountstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Accountstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Accountstatus), nil
}

type Entitytype string

const (
	EntitytypeHEADQUARTER Entitytype = "HEAD_QUARTER"
	EntitytypeHQAGENT     Entitytype = "HQ_AGENT"
	EntitytypeLV1AGENT    Entitytype = "LV1_AGENT"
	EntitytypeLV2AGENT    Entitytype = "LV2_AGENT"
	EntitytypeSTUDENT     Entitytype = "STUDENT"
)

func (e *Entitytype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Entitytype(s)
	case string:
		*e = Entitytype(s)
	default:
		return fmt.Errorf("unsupported scan type for Entitytype: %T", src)
	}
	return nil
}

type NullEntitytype struct {
	Entitytype Entitytype `json:"entitytype"`
	Valid      bool       `json:"valid"` // Valid is true if Entitytype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitytype) Scan(value interface{}) error {
	if value == nil {
		ns.Entitytype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Entitytype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitytype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Entitytype), nil
}

type Gender string

const (
	Gender0 Gender = "0"
	Gender1 Gender = "1"
	Gender2 Gender = "2"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type Inventoryorderstatus string

const (
	InventoryorderstatusPending  Inventoryorderstatus = "pending"
	InventoryorderstatusDeclined Inventoryorderstatus = "declined"
	InventoryorderstatusPaid     Inventoryorderstatus = "paid"
	InventoryorderstatusSettled  Inventoryorderstatus = "settled"
)

func (e *Inventoryorderstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Inventoryorderstatus(s)
	case string:
		*e = Inventoryorderstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Inventoryorderstatus: %T", src)
	}
	return nil
}

type NullInventoryorderstatus struct {
	Inventoryorderstatus Inventoryorderstatus `json:"inventoryorderstatus"`
	Valid                bool                 `json:"valid"` // Valid is true if Inventoryorderstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryorderstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Inventoryorderstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Inventoryorderstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryorderstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Inventoryorderstatus), nil
}

type Inventoryordertype string

const (
	InventoryordertypeHqInitiated Inventoryordertype = "hq_initiated"
	InventoryordertypeFromBalance Inventoryordertype = "from_balance"
	InventoryordertypeAgentTopup  Inventoryordertype = "agent_topup"
)

func (e *Inventoryordertype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Inventoryordertype(s)
	case string:
		*e = Inventoryordertype(s)
	default:
		return fmt.Errorf("unsupported scan type for Inventoryordertype: %T", src)
	}
	return nil
}

type NullInventoryordertype struct {
	Inventoryordertype Inventoryordertype `json:"inventoryordertype"`
	Valid              bool               `json:"valid"` // Valid is true if Inventoryordertype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryordertype) Scan(value interface{}) error {
	if value == nil {
		ns.Inventoryordertype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Inventoryordertype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryordertype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Inventoryordertype), nil
}

type Majortype string

const (
	MajortypeBACHELOR  Majortype = "BACHELOR"
	MajortypeASSOCIATE Majortype = "ASSOCIATE"
	MajortypeMASTER    Majortype = "MASTER"
	MajortypePHD       Majortype = "PHD"
)

func (e *Majortype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Majortype(s)
	case string:
		*e = Majortype(s)
	default:
		return fmt.Errorf("unsupported scan type for Majortype: %T", src)
	}
	return nil
}

type NullMajortype struct {
	Majortype Majortype `json:"majortype"`
	Valid     bool      `json:"valid"` // Valid is true if Majortype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMajortype) Scan(value interface{}) error {
	if value == nil {
		ns.Majortype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Majortype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMajortype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Majortype), nil
}

type Roletype string

const (
	RoletypeHQ      Roletype = "HQ"
	RoletypeAGENT   Roletype = "AGENT"
	RoletypeSTUDENT Roletype = "STUDENT"
)

func (e *Roletype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roletype(s)
	case string:
		*e = Roletype(s)
	default:
		return fmt.Errorf("unsupported scan type for Roletype: %T", src)
	}
	return nil
}

type NullRoletype struct {
	Roletype Roletype `json:"roletype"`
	Valid    bool     `json:"valid"` // Valid is true if Roletype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoletype) Scan(value interface{}) error {
	if value == nil {
		ns.Roletype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roletype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoletype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roletype), nil
}

type Withdrawtype string

const (
	WithdrawtypeBalance   Withdrawtype = "balance"
	WithdrawtypePartition Withdrawtype = "partition"
	WithdrawtypeTriple    Withdrawtype = "triple"
)

func (e *Withdrawtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Withdrawtype(s)
	case string:
		*e = Withdrawtype(s)
	default:
		return fmt.Errorf("unsupported scan type for Withdrawtype: %T", src)
	}
	return nil
}

type NullWithdrawtype struct {
	Withdrawtype Withdrawtype `json:"withdrawtype"`
	Valid        bool         `json:"valid"` // Valid is true if Withdrawtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawtype) Scan(value interface{}) error {
	if value == nil {
		ns.Withdrawtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Withdrawtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Withdrawtype), nil
}

type Account struct {
	ID                uuid.UUID            `json:"id"`
	Type              NullEntitytype       `json:"type"`
	Reservebalance    decimal.NullDecimal  `json:"reservebalance"`
	Balance           decimal.NullDecimal  `json:"balance"`
	Upstreamaccount   uuid.NullUUID        `json:"upstreamaccount"`
	Accountname       *string              `json:"accountname"`
	Status            NullAccountstatus    `json:"status"`
	Partition         NullAccountpartition `json:"partition"`
	Balanceleft       decimal.NullDecimal  `json:"balanceleft"`
	Balanceright      decimal.NullDecimal  `json:"balanceright"`
	Pendingreturn     decimal.NullDecimal  `json:"pendingreturn"`
	Balancetriple     decimal.NullDecimal  `json:"balancetriple"`
	Balancetriplelock decimal.NullDecimal  `json:"balancetriplelock"`
	Orgid             uuid.NullUUID        `json:"orgid"`
	Createdat         pgtype.Timestamp     `json:"createdat"`
	Updatedat         pgtype.Timestamp     `json:"updatedat"`
}

type Accountaddress struct {
	ID        uuid.UUID        `json:"id"`
	Accountid uuid.NullUUID    `json:"accountid"`
	Zip       int32            `json:"zip"`
	Province  string           `json:"province"`
	City      string           `json:"city"`
	District  string           `json:"district"`
	Address   string           `json:"address"`
	Isdefault bool             `json:"isdefault"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Accountsql struct {
	Accounttype Entitytype `json:"accounttype"`
	Accountid   uuid.UUID  `json:"accountid"`
	Sqlid       int32      `json:"sqlid"`
}

type Adjustment struct {
	ID            uuid.UUID          `json:"id"`
	Accountid     uuid.UUID          `json:"accountid"`
	Amount        decimal.Decimal    `json:"amount"`
	Balancetype   Accountbalancetype `json:"balancetype"`
	Type          uuid.NullUUID      `json:"type"`
	Notes         string             `json:"notes"`
	Operateuserid uuid.NullUUID      `json:"operateuserid"`
	Createdat     pgtype.Timestamp   `json:"createdat"`
}

type Agentattribute struct {
	Accountid                  uuid.UUID        `json:"accountid"`
	Province                   *string          `json:"province"`
	City                       *string          `json:"city"`
	Createdat                  pgtype.Timestamp `json:"createdat"`
	Updatedat                  pgtype.Timestamp `json:"updatedat"`
	Agentcode                  *string          `json:"agentcode"`
	Paymentmethodwechatoffline bool             `json:"paymentmethodwechatoffline"`
	Paymentmethodalipayoffline bool             `json:"paymentmethodalipayoffline"`
	Paymentmethodcardoffline   bool             `json:"paymentmethodcardoffline"`
	Paymentmethodwechatpay     bool             `json:"paymentmethodwechatpay"`
	Paymentmethodliuliupay     bool             `json:"paymentmethodliuliupay"`
	DemoFlag                   bool             `json:"demo_flag"`
	DemoAccount                uuid.NullUUID    `json:"demo_account"`
}

type Auditlog struct {
	AuditID   int32              `json:"audit_id"`
	TableName *string            `json:"table_name"`
	Operation interface{}        `json:"operation"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
	UserName  *string            `json:"user_name"`
	OldData   []byte             `json:"old_data"`
	NewData   []byte             `json:"new_data"`
}

type Balanceactivity struct {
	ID           uuid.UUID           `json:"id"`
	Source       *string             `json:"source"`
	Orderid      *int64              `json:"orderid"`
	Withdrawid   uuid.NullUUID       `json:"withdrawid"`
	Accountid    uuid.NullUUID       `json:"accountid"`
	Amount       decimal.NullDecimal `json:"amount"`
	Balanceafter decimal.NullDecimal `json:"balanceafter"`
	Createdat    pgtype.Timestamp    `json:"createdat"`
	Updatedat    pgtype.Timestamp    `json:"updatedat"`
}

type Casbinrule struct {
	PType string    `json:"p_type"`
	V0    uuid.UUID `json:"v0"`
	V1    uuid.UUID `json:"v1"`
	V2    string    `json:"v2"`
	V3    string    `json:"v3"`
	V4    string    `json:"v4"`
	V5    string    `json:"v5"`
}

type Company struct {
	ID        int32            `json:"id"`
	Path      *string          `json:"path"`
	Name      *string          `json:"name"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Customsql struct {
	ID            int32   `json:"id"`
	Description   string  `json:"description"`
	Query         string  `json:"query"`
	Param1name    *string `json:"param1name"`
	Param1default *string `json:"param1default"`
	Param2name    *string `json:"param2name"`
	Param2default *string `json:"param2default"`
	Param3name    *string `json:"param3name"`
	Param3default *string `json:"param3default"`
	Param4name    *string `json:"param4name"`
	Param4default *string `json:"param4default"`
	Param5name    *string `json:"param5name"`
	Param5default *string `json:"param5default"`
	Param6name    *string `json:"param6name"`
	Param6default *string `json:"param6default"`
	Param7name    *string `json:"param7name"`
	Param7default *string `json:"param7default"`
	Param8name    *string `json:"param8name"`
	Param8default *string `json:"param8default"`
	Param9name    *string `json:"param9name"`
	Param9default *string `json:"param9default"`
}

type Customsqlqueryhistory struct {
	ID            int32            `json:"id"`
	Userid        uuid.UUID        `json:"userid"`
	Sqlid         int32            `json:"sqlid"`
	Param1default *string          `json:"param1default"`
	Param2default *string          `json:"param2default"`
	Param3default *string          `json:"param3default"`
	Param4default *string          `json:"param4default"`
	Param5default *string          `json:"param5default"`
	Param6default *string          `json:"param6default"`
	Param7default *string          `json:"param7default"`
	Param8default *string          `json:"param8default"`
	Param9default *string          `json:"param9default"`
	Status        string           `json:"status"`
	Message       *string          `json:"message"`
	Createdat     pgtype.Timestamp `json:"createdat"`
	Updatedat     pgtype.Timestamp `json:"updatedat"`
}

type Datadictionary struct {
	Key       string  `json:"key"`
	Value     *string `json:"value"`
	Namespace *string `json:"namespace"`
}

type Entitlementtype struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

type Franchisefee struct {
	Agenttype   Entitytype      `json:"agenttype"`
	Price       decimal.Decimal `json:"price"`
	Description *string         `json:"description"`
}

type Franchiseorder struct {
	ID            uuid.UUID        `json:"id"`
	Accountid     uuid.UUID        `json:"accountid"`
	Status        *string          `json:"status"`
	Paymentmethod *string          `json:"paymentmethod"`
	Originaltype  NullEntitytype   `json:"originaltype"`
	Targettype    Entitytype       `json:"targettype"`
	Pendingfee    decimal.Decimal  `json:"pendingfee"`
	Createdat     pgtype.Timestamp `json:"createdat"`
	Updatedat     pgtype.Timestamp `json:"updatedat"`
}

type Goventerprise struct {
	ID      int16   `json:"id"`
	Name    *string `json:"name"`
	Website *string `json:"website"`
}

type Guardian struct {
	Guardianid   uuid.UUID        `json:"guardianid"`
	Studentid    uuid.NullUUID    `json:"studentid"`
	Relationship *string          `json:"relationship"`
	Createdat    pgtype.Timestamp `json:"createdat"`
	Updatedat    pgtype.Timestamp `json:"updatedat"`
}

type Inventoryorder struct {
	ID                interface{}          `json:"id"`
	Accountid         uuid.UUID            `json:"accountid"`
	Productid         uuid.UUID            `json:"productid"`
	Quantity          int32                `json:"quantity"`
	Type              Inventoryordertype   `json:"type"`
	Lastoperateuserid uuid.NullUUID        `json:"lastoperateuserid"`
	Status            Inventoryorderstatus `json:"status"`
	Paymentmethod     *string              `json:"paymentmethod"`
	Unitprice         decimal.NullDecimal  `json:"unitprice"`
	Payat             pgtype.Timestamp     `json:"payat"`
	Settledat         pgtype.Timestamp     `json:"settledat"`
	Createdat         pgtype.Timestamp     `json:"createdat"`
	Updatedat         pgtype.Timestamp     `json:"updatedat"`
}

type Inventoryorderproof struct {
	ID               uuid.UUID        `json:"id"`
	Inventoryorderid interface{}      `json:"inventoryorderid"`
	Imageurl         string           `json:"imageurl"`
	Createdat        pgtype.Timestamp `json:"createdat"`
}

type Invitationcode struct {
	Code       string           `json:"code"`
	Accountid  uuid.NullUUID    `json:"accountid"`
	Userid     uuid.NullUUID    `json:"userid"`
	Createtype NullEntitytype   `json:"createtype"`
	Createdat  pgtype.Timestamp `json:"createdat"`
	Expiresat  pgtype.Timestamp `json:"expiresat"`
	Updatedat  pgtype.Timestamp `json:"updatedat"`
}

type Liuliustatement struct {
	ID                uuid.UUID           `json:"id"`
	Transactionid     string              `json:"transactionid"`
	Transactiontime   pgtype.Timestamp    `json:"transactiontime"`
	Store             *string             `json:"store"`
	Cashier           *string             `json:"cashier"`
	Item              *string             `json:"item"`
	Paymentmethod     *string             `json:"paymentmethod"`
	Transactionamount decimal.Decimal     `json:"transactionamount"`
	Fee               decimal.NullDecimal `json:"fee"`
	Settleamount      decimal.NullDecimal `json:"settleamount"`
	Memo              *string             `json:"memo"`
	Filename          *string             `json:"filename"`
	Orderid           *int64              `json:"orderid"`
	Createdat         pgtype.Timestamp    `json:"createdat"`
	Updatedat         pgtype.Timestamp    `json:"updatedat"`
	Automationlog     *string             `json:"automationlog"`
}

type Major struct {
	Code               string        `json:"code"`
	Name               *string       `json:"name"`
	Faculty            *string       `json:"faculty"`
	Department         *string       `json:"department"`
	Studyingsuggestion *string       `json:"studyingsuggestion"`
	Majorreference     *string       `json:"majorreference"`
	Type               NullMajortype `json:"type"`
	Postgradsuggestion *string       `json:"postgradsuggestion"`
}

type Majorenterprise struct {
	Majorcode    string `json:"majorcode"`
	Enterpriseid int16  `json:"enterpriseid"`
}

type Mbtisuggestion struct {
	ID         int32   `json:"id"`
	Type       *string `json:"type"`
	Suggestion *string `json:"suggestion"`
}

type MvBalanceActivityDetail struct {
	Orderid          *int64              `json:"orderid"`
	Createdat        pgtype.Timestamp    `json:"createdat"`
	Accountid        uuid.NullUUID       `json:"accountid"`
	Source           *string             `json:"source"`
	Productname      interface{}         `json:"productname"`
	ChildAccountname *string             `json:"child_accountname"`
	ChildAccountType NullEntitytype      `json:"child_account_type"`
	Amount           decimal.NullDecimal `json:"amount"`
	Balanceafter     decimal.NullDecimal `json:"balanceafter"`
}

type Order struct {
	ID            int64               `json:"id"`
	Status        *string             `json:"status"`
	Studentid     uuid.NullUUID       `json:"studentid"`
	Paymentmethod *string             `json:"paymentmethod"`
	Price         decimal.NullDecimal `json:"price"`
	Createdat     pgtype.Timestamp    `json:"createdat"`
	Payat         pgtype.Timestamp    `json:"payat"`
	Updatedat     pgtype.Timestamp    `json:"updatedat"`
	Settledat     pgtype.Timestamp    `json:"settledat"`
}

type Ordercoupon struct {
	Code            int64               `json:"code"`
	Agentid         uuid.UUID           `json:"agentid"`
	Issuinguser     uuid.UUID           `json:"issuinguser"`
	Discountamount  decimal.NullDecimal `json:"discountamount"`
	Maxcount        *int32              `json:"maxcount"`
	Productid       uuid.NullUUID       `json:"productid"`
	Studentid       uuid.NullUUID       `json:"studentid"`
	Effectstartdate pgtype.Date         `json:"effectstartdate"`
	Effectduedate   pgtype.Date         `json:"effectduedate"`
	Createdat       pgtype.Timestamp    `json:"createdat"`
	Lastusedat      pgtype.Timestamp    `json:"lastusedat"`
}

type Orderofflinepayproof struct {
	Orderid   int64            `json:"orderid"`
	Imageurl  string           `json:"imageurl"`
	ID        uuid.UUID        `json:"id"`
	Createdat pgtype.Timestamp `json:"createdat"`
}

type Orderproduct struct {
	ID            int64               `json:"id"`
	Orderid       *int64              `json:"orderid"`
	Productid     uuid.NullUUID       `json:"productid"`
	Originalprice decimal.NullDecimal `json:"originalprice"`
	Couponcode    *int64              `json:"couponcode"`
	Actualprice   decimal.NullDecimal `json:"actualprice"`
}

type Ordertag struct {
	Orderid int64  `json:"orderid"`
	Tag     string `json:"tag"`
}

type Organization struct {
	ID            uuid.UUID        `json:"id"`
	Uri           string           `json:"uri"`
	Rootaccountid uuid.NullUUID    `json:"rootaccountid"`
	Config        []byte           `json:"config"`
	Isinherit     bool             `json:"isinherit"`
	Logourl       *string          `json:"logourl"`
	Sitename      *string          `json:"sitename"`
	Wxappid       *string          `json:"wxappid"`
	Wxappsecret   *string          `json:"wxappsecret"`
	Redirecturl   *string          `json:"redirecturl"`
	Createdat     pgtype.Timestamp `json:"createdat"`
}

type Orgprivilege struct {
	ID        uuid.UUID        `json:"id"`
	Orgid     uuid.NullUUID    `json:"orgid"`
	Privname  string           `json:"privname"`
	Isallow   *bool            `json:"isallow"`
	Isdeny    *bool            `json:"isdeny"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Partitionaward struct {
	ID               int32               `json:"id"`
	Accountid        uuid.UUID           `json:"accountid"`
	Salesaccountid   uuid.UUID           `json:"salesaccountid"`
	Amount           decimal.NullDecimal `json:"amount"`
	Orderid          *int64              `json:"orderid"`
	Linkedaccountid  uuid.NullUUID       `json:"linkedaccountid"`
	Partition        Accountpartition    `json:"partition"`
	Franchiseorderid uuid.NullUUID       `json:"franchiseorderid"`
	Createdat        pgtype.Timestamp    `json:"createdat"`
}

type Privilege struct {
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Createdat   pgtype.Timestamp `json:"createdat"`
}

type Product struct {
	ID              uuid.UUID        `json:"id"`
	Type            *string          `json:"type"`
	Productname     string           `json:"productname"`
	Finalprice      decimal.Decimal  `json:"finalprice"`
	Publishstatus   bool             `json:"publishstatus"`
	Description     string           `json:"description"`
	Purchaselimit   *int16           `json:"purchaselimit"`
	Pricingschedule []byte           `json:"pricingschedule"`
	Createdat       pgtype.Timestamp `json:"createdat"`
	Updatedat       pgtype.Timestamp `json:"updatedat"`
}

type Productentitlementtype struct {
	Productid         uuid.UUID `json:"productid"`
	Entitlementtypeid uuid.UUID `json:"entitlementtypeid"`
	Validdays         *int32    `json:"validdays"`
}

type Productimage struct {
	ID          uuid.UUID     `json:"id"`
	Productid   uuid.NullUUID `json:"productid"`
	Imageurl    *string       `json:"imageurl"`
	Ismaster    *bool         `json:"ismaster"`
	Imageorder  *int16        `json:"imageorder"`
	Imagestatus *bool         `json:"imagestatus"`
}

type Productinventory struct {
	ID                   uuid.UUID        `json:"id"`
	Accountid            uuid.UUID        `json:"accountid"`
	Productid            uuid.UUID        `json:"productid"`
	Quantity             int32            `json:"quantity"`
	Lastinventoryorderid interface{}      `json:"lastinventoryorderid"`
	Lastorderid          *int64           `json:"lastorderid"`
	Createdat            pgtype.Timestamp `json:"createdat"`
	Updatedat            pgtype.Timestamp `json:"updatedat"`
}

type Productinventoryhistory struct {
	ID               int32            `json:"id"`
	Sourceid         uuid.UUID        `json:"sourceid"`
	Quantity         int32            `json:"quantity"`
	Inventoryorderid interface{}      `json:"inventoryorderid"`
	Orderid          *int64           `json:"orderid"`
	Quantityafter    int32            `json:"quantityafter"`
	Createdat        pgtype.Timestamp `json:"createdat"`
}

type Productpriceoverwrite struct {
	ID                  uuid.UUID           `json:"id"`
	Rootproduct         uuid.NullUUID       `json:"rootproduct"`
	Name                string              `json:"name"`
	Downstreamaccountid uuid.NullUUID       `json:"downstreamaccountid"`
	Price               decimal.NullDecimal `json:"price"`
	Createdat           pgtype.Timestamp    `json:"createdat"`
	Updatedat           pgtype.Timestamp    `json:"updatedat"`
}

type Projectdelivery struct {
	ID              uuid.UUID           `json:"id"`
	Orderproductid  *int64              `json:"orderproductid"`
	Deliveryaccount uuid.NullUUID       `json:"deliveryaccount"`
	Price           decimal.NullDecimal `json:"price"`
	Status          *string             `json:"status"`
	Source          *string             `json:"source"`
	Assignmode      *string             `json:"assignmode"`
	Starttime       pgtype.Timestamp    `json:"starttime"`
	Endtime         pgtype.Timestamp    `json:"endtime"`
	Createdat       pgtype.Timestamp    `json:"createdat"`
	Updatedat       pgtype.Timestamp    `json:"updatedat"`
}

type Qianliaocoupon struct {
	ID         int32            `json:"id"`
	Couponcode *string          `json:"couponcode"`
	Studentid  uuid.NullUUID    `json:"studentid"`
	Createdat  pgtype.Timestamp `json:"createdat"`
	Updatedat  pgtype.Timestamp `json:"updatedat"`
}

type Recruit struct {
	ID              int32            `json:"id"`
	Sharecount      *int32           `json:"sharecount"`
	Browsecount     *int32           `json:"browsecount"`
	Favoritecount   *int32           `json:"favoritecount"`
	Recruitid       int32            `json:"recruitid"`
	Companyname     *string          `json:"companyname"`
	Logourl         *string          `json:"logourl"`
	Enterprisename  *string          `json:"enterprisename"`
	Tag             *string          `json:"tag"`
	Citynamelist    *string          `json:"citynamelist"`
	Createtype      pgtype.Timestamp `json:"createtype"`
	Updatetime      pgtype.Timestamp `json:"updatetime"`
	Companytype     *string          `json:"companytype"`
	Isrecommended   *bool            `json:"isrecommended"`
	Content         *string          `json:"content"`
	Url             *string          `json:"url"`
	Begintime       pgtype.Date      `json:"begintime"`
	Endtime         pgtype.Date      `json:"endtime"`
	Overseasstudent *string          `json:"overseasstudent"`
	Domesticstudent *string          `json:"domesticstudent"`
	Releasesource   *string          `json:"releasesource"`
}

type Role struct {
	ID          uuid.UUID        `json:"id"`
	Rolename    string           `json:"rolename"`
	Accountkind Roletype         `json:"accountkind"`
	Issystem    bool             `json:"issystem"`
	RolenameCn  *string          `json:"rolename_cn"`
	Createdat   pgtype.Timestamp `json:"createdat"`
	Updatedat   pgtype.Timestamp `json:"updatedat"`
}

type Roleprivilege struct {
	ID        uuid.UUID        `json:"id"`
	Roleid    uuid.UUID        `json:"roleid"`
	Privname  string           `json:"privname"`
	Isallow   *bool            `json:"isallow"`
	Isdeny    *bool            `json:"isdeny"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Showcasepagecarouseldatum struct {
	ID        int32            `json:"id"`
	Imagelink *string          `json:"imagelink"`
	Extlink   *string          `json:"extlink"`
	Company   *string          `json:"company"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Showcasepageitemdatum struct {
	ID         int32            `json:"id"`
	Imagelink  *string          `json:"imagelink"`
	Extlink    *string          `json:"extlink"`
	Company    *string          `json:"company"`
	Title      *string          `json:"title"`
	Grouptitle *string          `json:"grouptitle"`
	Createdat  pgtype.Timestamp `json:"createdat"`
	Updatedat  pgtype.Timestamp `json:"updatedat"`
}

type Studentattribute struct {
	Accountid       uuid.UUID        `json:"accountid"`
	University      *string          `json:"university"`
	Majorcode       *string          `json:"majorcode"`
	Mbtienergy      *string          `json:"mbtienergy"`
	Mbtimind        *string          `json:"mbtimind"`
	Mbtidecision    *string          `json:"mbtidecision"`
	Mbtireaction    *string          `json:"mbtireaction"`
	Studysuggestion *string          `json:"studysuggestion"`
	EntryDate       pgtype.Date      `json:"entry_date"`
	DegreeYears     *int16           `json:"degree_years"`
	Grade           *int16           `json:"grade"`
	Semester        *int16           `json:"semester"`
	Degree          NullMajortype    `json:"degree"`
	TotalScore      *float64         `json:"total_score"`
	Chinese         *float64         `json:"chinese"`
	Mathematics     *float64         `json:"mathematics"`
	ForeignLanguage *float64         `json:"foreign_language"`
	Physics         *float64         `json:"physics"`
	Chemistry       *float64         `json:"chemistry"`
	Biology         *float64         `json:"biology"`
	Politics        *float64         `json:"politics"`
	History         *float64         `json:"history"`
	Geography       *float64         `json:"geography"`
	Createdat       pgtype.Timestamp `json:"createdat"`
	Updatedat       pgtype.Timestamp `json:"updatedat"`
}

type Studententitlement struct {
	ID                uuid.UUID        `json:"id"`
	Studentid         uuid.NullUUID    `json:"studentid"`
	Entitlementtypeid uuid.NullUUID    `json:"entitlementtypeid"`
	Lastorderid       *int64           `json:"lastorderid"`
	Createdat         pgtype.Timestamp `json:"createdat"`
	Expiresat         pgtype.Timestamp `json:"expiresat"`
	Updatedat         pgtype.Timestamp `json:"updatedat"`
}

type Studenttag struct {
	Studentid uuid.UUID `json:"studentid"`
	Tag       string    `json:"tag"`
}

type Tripleawardhistory struct {
	ID                 int32            `json:"id"`
	Sourceid           uuid.UUID        `json:"sourceid"`
	Amount             decimal.Decimal  `json:"amount"`
	Orderid            int64            `json:"orderid"`
	Pendingreturnafter decimal.Decimal  `json:"pendingreturnafter"`
	Createdat          pgtype.Timestamp `json:"createdat"`
}

type Triplecycleaward struct {
	Accountid        uuid.UUID        `json:"accountid"`
	Number           int32            `json:"number"`
	Linkedaccountid  uuid.UUID        `json:"linkedaccountid"`
	Originaltype     NullEntitytype   `json:"originaltype"`
	Targettype       Entitytype       `json:"targettype"`
	Amount           decimal.Decimal  `json:"amount"`
	Pendingreturn    decimal.Decimal  `json:"pendingreturn"`
	Createdat        pgtype.Timestamp `json:"createdat"`
	Updatedat        pgtype.Timestamp `json:"updatedat"`
	Franchiseorderid uuid.NullUUID    `json:"franchiseorderid"`
	ID               uuid.UUID        `json:"id"`
}

type University struct {
	Schoolname         string  `json:"schoolname"`
	Location           *string `json:"location"`
	Level              *string `json:"level"`
	Remark             *string `json:"remark"`
	Isgraduateeligible *bool   `json:"isgraduateeligible"`
}

type User struct {
	ID            uuid.UUID        `json:"id"`
	Password      string           `json:"password"`
	Phone         string           `json:"phone"`
	Email         *string          `json:"email"`
	Nickname      string           `json:"nickname"`
	Aliasname     *string          `json:"aliasname"`
	Firstname     *string          `json:"firstname"`
	Lastname      *string          `json:"lastname"`
	Wechatopenid  *string          `json:"wechatopenid"`
	Wechatunionid *string          `json:"wechatunionid"`
	Sex           Gender           `json:"sex"`
	Province      *string          `json:"province"`
	City          *string          `json:"city"`
	Birthdate     pgtype.Date      `json:"birthdate"`
	Avatarurl     *string          `json:"avatarurl"`
	Status        string           `json:"status"`
	Source        *string          `json:"source"`
	Referaluserid uuid.NullUUID    `json:"referaluserid"`
	Createdat     pgtype.Timestamp `json:"createdat"`
	Updatedat     pgtype.Timestamp `json:"updatedat"`
}

type Useraccountrole struct {
	ID        uuid.UUID        `json:"id"`
	Userid    uuid.UUID        `json:"userid"`
	Accountid uuid.UUID        `json:"accountid"`
	Roleid    uuid.UUID        `json:"roleid"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Userwithdrawmethod struct {
	ID             uuid.UUID        `json:"id"`
	Userid         uuid.UUID        `json:"userid"`
	Withdrawmethod string           `json:"withdrawmethod"`
	Accountname    *string          `json:"accountname"`
	Accountnumber  *string          `json:"accountnumber"`
	Bank           *string          `json:"bank"`
	Createdat      pgtype.Timestamp `json:"createdat"`
	Updatedat      pgtype.Timestamp `json:"updatedat"`
}

type VStudentdetail struct {
	Studentid          uuid.UUID        `json:"studentid"`
	Agentid            uuid.NullUUID    `json:"agentid"`
	Studentname        *string          `json:"studentname"`
	Createdat          pgtype.Timestamp `json:"createdat"`
	Studentphone       *string          `json:"studentphone"`
	Studentwechatname  *string          `json:"studentwechatname"`
	Studentemail       *string          `json:"studentemail"`
	Guardianphone      *string          `json:"guardianphone"`
	Guardianwechatname *string          `json:"guardianwechatname"`
	Guardianemail      *string          `json:"guardianemail"`
	Relationship       *string          `json:"relationship"`
	Purchasedproduct   interface{}      `json:"purchasedproduct"`
	Tags               interface{}      `json:"tags"`
}

type VUser struct {
	ID            uuid.UUID        `json:"id"`
	Password      string           `json:"password"`
	Phone         string           `json:"phone"`
	Email         *string          `json:"email"`
	Nickname      string           `json:"nickname"`
	Aliasname     *string          `json:"aliasname"`
	Firstname     *string          `json:"firstname"`
	Lastname      *string          `json:"lastname"`
	Wechatopenid  *string          `json:"wechatopenid"`
	Wechatunionid *string          `json:"wechatunionid"`
	Sex           Gender           `json:"sex"`
	Province      *string          `json:"province"`
	City          *string          `json:"city"`
	Birthdate     pgtype.Date      `json:"birthdate"`
	Avatarurl     *string          `json:"avatarurl"`
	Status        string           `json:"status"`
	Source        *string          `json:"source"`
	Referaluserid uuid.NullUUID    `json:"referaluserid"`
	Createdat     pgtype.Timestamp `json:"createdat"`
	Updatedat     pgtype.Timestamp `json:"updatedat"`
	Usertype      string           `json:"usertype"`
}

type Withdraw struct {
	ID                   interface{}         `json:"id"`
	Accountid            uuid.NullUUID       `json:"accountid"`
	Amount               decimal.NullDecimal `json:"amount"`
	Status               *string             `json:"status"`
	Type                 Withdrawtype        `json:"type"`
	Memo                 *string             `json:"memo"`
	Lastoperateuserid    uuid.NullUUID       `json:"lastoperateuserid"`
	Userwithdrawmethodid uuid.NullUUID       `json:"userwithdrawmethodid"`
	Createdat            pgtype.Timestamp    `json:"createdat"`
	Updatedat            pgtype.Timestamp    `json:"updatedat"`
}

type Withdrawattachment struct {
	ID         uuid.UUID     `json:"id"`
	Withdrawid uuid.NullUUID `json:"withdrawid"`
	Imageurl   *string       `json:"imageurl"`
}
