// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"xiandeng.net.cn/server/db"
	"xiandeng.net.cn/server/pkg/config"
	"xiandeng.net.cn/server/pkg/log"
	"xiandeng.net.cn/server/tasks/server"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (server.TaskServer, func(), error) {
	dbtx, err := db.NewDBTX(configConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := db.NewRepository(dbtx, logger)
	taskServer := server.NewTaskServer(configConfig, repository)
	return taskServer, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(db.NewDBTX, db.NewRepository)
