// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"xiandeng.net.cn/server/db"
	"xiandeng.net.cn/server/internal/app"
	"xiandeng.net.cn/server/internal/controller"
	"xiandeng.net.cn/server/internal/middlewares"
	"xiandeng.net.cn/server/internal/routers"
	"xiandeng.net.cn/server/internal/services"
	"xiandeng.net.cn/server/pkg/config"
	"xiandeng.net.cn/server/pkg/imap"
	"xiandeng.net.cn/server/pkg/jwt"
	"xiandeng.net.cn/server/pkg/log"
	"xiandeng.net.cn/server/pkg/oss"
	"xiandeng.net.cn/server/pkg/rbac"
	"xiandeng.net.cn/server/pkg/resource"
	"xiandeng.net.cn/server/pkg/validate"
	"xiandeng.net.cn/server/pkg/wechat"
	"xiandeng.net.cn/server/pkg/wechatpay"
	"xiandeng.net.cn/server/services/cache"
	"xiandeng.net.cn/server/tasks/server"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (*app.WebServer, func(), error) {
	dbtx, err := db.NewDBTX(configConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := db.NewRepository(dbtx, logger)
	jwtManager := jwt.NewJwtManager(configConfig)
	wxServiceManager := wechat.NewWxServiceManager(repository, configConfig)
	authService := services.NewAuthService(configConfig, logger, repository, wxServiceManager)
	userMiddleware := middlewares.NewUserMiddleware(repository, jwtManager, authService)
	controllerController := controller.NewController(logger, configConfig)
	ossClient := oss.NewOSSClient(configConfig)
	resourceResource := resource.NewResource(configConfig, ossClient)
	resourceService := services.NewResourceService(configConfig, logger, repository, resourceResource)
	globalCache := cache.GetAppCache()
	enforcer := rbac.NewEnforcer(configConfig)
	validatorValidate := validate.NewValidator()
	authController := controller.NewAuthController(controllerController, authService, resourceService, jwtManager, globalCache, wxServiceManager, enforcer, validatorValidate)
	accountService := services.NewAccountService(configConfig, logger, repository)
	accountController := controller.NewAccountController(controllerController, accountService)
	resourceController := controller.NewResourceController(controllerController, resourceService, repository, ossClient)
	invitationCodeService := services.NewInvitationCodeService(configConfig, logger, repository, globalCache)
	userService := services.NewUserService(configConfig, logger, repository, globalCache)
	invitationCodeController := controller.NewInvitationCodeController(controllerController, invitationCodeService, userService)
	taskClient := server.NewTaskClient(configConfig)
	studentService := services.NewStudentService(configConfig, logger, repository, taskClient)
	studentController := controller.NewStudentController(controllerController, studentService, taskClient, repository, validatorValidate)
	couponService := services.NewCouponService(configConfig, logger, repository)
	couponController := controller.NewCouponController(controllerController, couponService, repository)
	orderService := services.NewOrderService(configConfig, logger, repository, taskClient)
	paymentGeneralService := services.NewPaymentGeneralService(configConfig, logger, repository)
	orderController := controller.NewOrderController(controllerController, orderService, paymentGeneralService, taskClient, repository, validatorValidate)
	wechatPayEngine := wechatpay.NewWechatPayEngine(configConfig)
	wechatpayService := services.NewWechatpayService(configConfig, logger, repository, wechatPayEngine)
	wechatpayController := controller.NewWechatpayController(controllerController, wechatpayService, paymentGeneralService, repository)
	productService := services.NewProductService(configConfig, logger, repository)
	productController := controller.NewProductController(controllerController, productService, repository)
	fileSystemService := services.NewFileSystemService(configConfig, ossClient)
	imapClient := imap.NewImapClient(configConfig)
	imapService := services.NewImapService(imapClient)
	dataService := services.NewDataService(configConfig, logger, repository)
	systemController := controller.NewSystemController(controllerController, taskClient, fileSystemService, imapService, dataService)
	walletController := controller.NewWalletController(controllerController, repository)
	officialAccount := wechat.NewOfficialAccount(configConfig)
	officialAccountController := controller.NewOfficialAccountController(controllerController, officialAccount)
	userController := controller.NewUserController(controllerController, repository, authService, resourceService)
	showcaseService := services.NewShowcaseService(configConfig, logger, repository)
	showcaseController := controller.NewShowcaseController(controllerController, showcaseService)
	paymentController := controller.NewPaymentController(controllerController, paymentGeneralService, taskClient, repository)
	withdrawService := services.NewWithdrawService(configConfig, logger, repository)
	withdrawController := controller.NewWithdrawController(controllerController, withdrawService, validatorValidate)
	deliveryService := services.NewDeliveryService(configConfig, logger, repository)
	deliveryController := controller.NewDeliveryController(controllerController, deliveryService)
	inventoryService := services.NewInventoryService(configConfig, logger, repository)
	inventoryController := controller.NewInventoryController(controllerController, inventoryService, validatorValidate)
	adjustmentService := services.NewAdjustmentService(configConfig, logger, repository)
	adjustmentController := controller.NewAdjustmentController(controllerController, adjustmentService)
	deps := router.Deps{
		UserMiddleware:           userMiddleware,
		AuthController:           authController,
		AccountController:        accountController,
		ResourceController:       resourceController,
		InvitationCodeController: invitationCodeController,
		StudentController:        studentController,
		CouponController:         couponController,
		OrderController:          orderController,
		WechatpayController:      wechatpayController,
		ProductController:        productController,
		SystemController:         systemController,
		BalanceController:        walletController,
		OfficialAccountController: officialAccountController,
		UserController:             userController,
		ShowcaseController:        showcaseController,
		PaymentController:         paymentController,
		WithdrawController:        withdrawController,
		DeliveryController:        deliveryController,
		InventoryController:       inventoryController,
		AdjustmentController:      adjustmentController,
	}
	webServer, err := router.NewAppServer(logger, configConfig, deps)
	if err != nil {
		return nil, nil, err
	}
	return webServer, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(db.NewDBTX, db.NewRepository)

var serviceSet = wire.NewSet(services.NewService, services.NewAuthService, services.NewUserService, services.NewCouponService, services.NewOrderService, services.NewWechatpayService, services.NewResourceService, services.NewAccountService, services.NewStudentService, services.NewInvitationCodeService, services.NewPaymentGeneralService, services.NewProductService, services.NewShowcaseService, services.NewFileSystemService, services.NewImapService, services.NewDataService, services.NewWithdrawService, services.NewDeliveryService, services.NewInventoryService, services.NewAdjustmentService)

var controllerSet = wire.NewSet(controller.NewController, controller.NewAuthController, controller.NewCouponController, controller.NewOrderController, controller.NewWechatpayController, controller.NewAccountController, controller.NewStudentController, controller.NewResourceController, controller.NewInvitationCodeController, controller.NewWalletController, controller.NewProductController, controller.NewSystemController, controller.NewOfficialAccountController, controller.NewUserController, controller.NewShowcaseController, controller.NewPaymentController, controller.NewWithdrawController, controller.NewDeliveryController, controller.NewInventoryController, controller.NewAdjustmentController)

var middlewareSet = wire.NewSet(middlewares.NewUserMiddleware)

var routerSet = wire.NewSet(wire.Struct(new(router.Deps), "*"), router.NewAppServer)
